export default {
  ACCOUNT_ADD: '@@ACCOUNT/ADD',
  ACCOUNT_RECEIVE_MONEY: '@@ACCOUNT/ACCOUNT_RECEIVE_MONEY',
  LOAD_CURRENCY_NAMES_REQUEST: '@@CURRENCY/LOAD_NAMES_REQUEST',
  LOAD_CURRENCY_NAMES_SUCCESS: '@@CURRENCY/LOAD_NAMES_SUCCESS',
  LOAD_CURRENCY_NAMES_FAILURE: '@@CURRENCY/LOAD_NAMES_FAILURE',
  LOAD_CURRENCY_SYMBOLS_REQUEST: '@@CURRENCY/LOAD_SYMBOLS_REQUEST',
  LOAD_CURRENCY_SYMBOLS_SUCCESS: '@@CURRENCY/LOAD_SYMBOLS_SUCCESS',
  LOAD_CURRENCY_SYMBOLS_FAILURE: '@@CURRENCY/LOAD_SYMBOLS_FAILURE',
}
